const STEPS = {
  START: "START",
  REGISTER_CONSENT: "REGISTER_CONSENT",
  PRE_REGISTER: "PRE_REGISTER",
  PRE_REGISTER_FORM: "PRE_REGISTER_FORM",
  CONSENT: "CONSENT",
  CONSENT_FAIL: "CONSENT_FAIL",
  REGISTER_FORM: "RESISTER_FORM",
  PRE_ENROLL: "PRE_ENROLL",
  ENROLL: "ENROLL",
  PRE_DRIVERLICENSE: "PRE_DRIVERLICENSE",
  DRIVERLICENSE: "DRIVERLICENSE",
  SWITCH_DEVICE: "SWITCH_DEVICE",
  ADDITIONAL_REQUIREMENTS: "ADDITIONAL_REQUIREMENTS",
  SUCCESS: "SUCCESS",
};

export default STEPS;
