const STEPS = {
    START:"START",
    CONSENT:"CONSENT",
    CONSENT_FAIL:"CONSENT_FAIL",
    REGISTER_FORM: "RESISTER_FORM",
    ENROLL:"ENROLL",
    DRIVERLICENSE:"DRIVERLICENSE",
    SWITCH_DEVICE: "SWITCH_DEVICE",
    ADDITIONAL_REQUIREMENTS: "ADDITIONAL_REQUIREMENTS",
    SUCCESS: "SUCCESS",
}

export default STEPS;